// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpaivcsnmtfxpdjsorch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYWl2Y3NubXRmeHBkanNvcmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDM3MzMsImV4cCI6MjA3MDI3OTczM30.WHt8ns3-lgos6tnZ-0Kz3_pfmJthPk0ti4cw9LcPIhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});